version: '3.8'

services:
  ladashy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ladashy
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
    networks:
      - homelab
    restart: unless-stopped

  ladashy-frontend:
    image: nginx:alpine
    container_name: ladashy-frontend
    ports:
      - "8080:80"
    volumes:
      - ../frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ladashy
    networks:
      - homelab
    restart: unless-stopped

networks:
  homelab:
    driver: bridge
